spring:
  application:
    name: api-gateway

  cloud:
    zookeeper:
      enabled: ${ZOOKEEPER_ENABLED:false}
      connect-string: ${ZOOKEEPER_CONNECT:localhost:2181}

    gateway:
      server:
        webmvc:
          routes:
            - id: github-webhooks
              uri: http://localhost:8190
              predicates:
                - Path=/api/v1/github/webhooks

            - id: identityservice
              uri: http://localhost:8190
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**

            - id: identityservice-oauth
              uri: http://localhost:8190
              predicates:
                - Path=/oauth2/**,/login/oauth2/**

            - id: urlservice-api
              uri: http://localhost:8191
              predicates:
                - Path=/api/v1/urls/**

            - id: urlservice-redirect
              uri: http://localhost:8191
              predicates:
                - Path=/s/{shortCode}
                - Method=GET

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

application:
  security:
    jwt:
      secret: ${JWT_SECRET:dev-secret-key-with-at-least-32-characters}
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.servlet.function: TRACE
    org.springframework.boot.autoconfigure.web: DEBUG