spring:
  application:
    name: urlservice
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shortlink_url_db?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8191

management:
  endpoints:
    web:
      exposure:
        include: health,info
